# Generated by Django 4.1.7 on 2023-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=256)),
                ("last", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
            ],
        ),
    ]
